


/**
 * insert products
 */
INSERT INTO product_entity (product_uuid, user_uuid, tag_uuid, name, number_of_downloads, creation_date, description) VALUES (random_uuid(), 'c848cad7c3b2499a96888fb2a261313b', '2D1EBC5B7D2741979CF0E84451C5BBB1', 'product 12',   125, TO_TIMESTAMP('2016-02-13 03:21:34.372', 'yyyy-mm-dd hh24:mi.ss.ff'), 'Obacht! Das fatal Schwedenfilm. Des ausgemergelt Gemächt bauchpinseln. Hochstapler und Geschmeide verhaspeln altbacken Damenbart. Franzosenkrankheit und Lümmeltüte katzbuckeln bierernst Haudegen. Die Schabracke schlampampen des fidel Absacker. Fressalien und Eisbein anschwärzen bräsig Begrüßungsgeld. Das hanebüchen Jubelperser. Mumpitz und Libero abkupfern töricht Flegel. Dem blümerant Gedudel duellieren. Dem pfundig Aue frohlocken. Ei der Daus!');
INSERT INTO product_entity (product_uuid, user_uuid, tag_uuid, name, number_of_downloads, creation_date, description) VALUES (random_uuid(), 'c848cad7c3b2499a96888fb2a261313b', '2D1EBC5B7D2741979CF0E84451C5BBB1', 'product 13',    25, TO_TIMESTAMP('2015-02-13 23:22:34.372', 'yyyy-mm-dd hh24:mi.ss.ff'), 'Obacht! Dem flügge Sättigungsbeilage. Bagage und Waldschrat idel Absacker. Fressalien und Eisbein anschwärzen bräsig Begrüßungsgeld. Das hanebüchen Jubelperser. Mumpitz und Libero abkupfern töricht Flegel. Dem blümerant Gedudel duellieren. Dem pfundig Aue frohlocken. Ei der Daus!');
INSERT INTO product_entity (product_uuid, user_uuid, tag_uuid, name, number_of_downloads, creation_date, description) VALUES (random_uuid(), 'c848cad7c3b2499a96888fb2a261313b', '2D1EBC5B7D2741979CF0E84451C5BBB1', 'product 14', 12125, TO_TIMESTAMP('2017-01-13 12:32:34.372', 'yyyy-mm-dd hh24:mi.ss.ff'), 'Fressalien und Eisbein anschwärzen bräsig Begrüßungsgeld. Das hanebüchen Jubelperser. Mumpitz und Libero abkupfern töricht Flegel. Dem blümerant Gedudel duellieren. Dem pfundig Aue frohlocken. Ei der Daus!');
INSERT INTO product_entity (product_uuid, user_uuid, tag_uuid, name, number_of_downloads, creation_date, description) VALUES (random_uuid(), '23c61362911e4438876507b019949570', '27497c552d0e4e8d88c68ad2721d94c7', 'product 15',  1125, TO_TIMESTAMP('2017-02-12 16:34:34.372', 'yyyy-mm-dd hh24:mi.ss.ff'), 'Obacht! Dem flügge SättigunGemächt bauchpinseln.');
INSERT INTO product_entity (product_uuid, user_uuid, tag_uuid, name, number_of_downloads, creation_date, description) VALUES (random_uuid(), '23c61362911e4438876507b019949570', '2D1EBC5B7D2741979CF0E84451C5BBB1', 'product 16',     5, TO_TIMESTAMP('2017-02-11 17:45:34.372', 'yyyy-mm-dd hh24:mi.ss.ff'), 'Obacht! Dem flügge Sättiggemergelt Gemächt bauchpinseln. Hochstapler und Geschmeide verhaspeln altbacken Damenbart. Franzosenkrankheit und Lümmeltüte katzbuckeln bierernst Haudegen. Die Schabracke schlampampen des fidel Absacker. Ei der Daus!');
INSERT INTO product_entity (product_uuid, user_uuid, tag_uuid, name, number_of_downloads, creation_date, description) VALUES (random_uuid(), 'c848cad7c3b2499a96888fb2a261313b', '2D1EBC5B7D2741979CF0E84451C5BBB1', 'product 17',    12, TO_TIMESTAMP('2015-12-13 18:08:34.372', 'yyyy-mm-dd hh24:mi.ss.ff'), 'Obacht! Dem flügge Sättigungsbeilage. as hanebüchen Jubelperser. Mumpitz und Libero abkupfern töricht Flegel. Dem blümerant Gedudel duellieren. Dem pfundig Aue frohlocken. Ei der Daus!');
INSERT INTO product_entity (product_uuid, user_uuid, tag_uuid, name, number_of_downloads, creation_date, description) VALUES (random_uuid(), 'c848cad7c3b2499a96888fb2a261313b', '27497c552d0e4e8d88c68ad2721d94c7', 'PRODUCT 18', 54125, TO_TIMESTAMP('2015-02-25 18:16:34.372', 'yyyy-mm-dd hh24:mi.ss.ff'), 'Obacht! Dem flügge Sättigungsbeilage. Bagage und Waldschrat betören hochnäsig Augenschmaus. Dem blindwütig Ohrenschmaus festnageln. Das fatal Schwedenfilm. Des ausgemergelt Gemächt bauchpinseln. Hochstapler und Geschmeide hanebüchen Jubelperser. Mumpitz und Libero abkupfern töricht Flegel. Dem blümerant Gedudel duellieren. Dem pfundig Aue frohlocken. Ei der Daus!');
INSERT INTO product_entity (product_uuid, user_uuid, tag_uuid, name, number_of_downloads, creation_date, description) VALUES (random_uuid(), 'c848cad7c3b2499a96888fb2a261313b', '2D1EBC5B7D2741979CF0E84451C5BBB1', 'PRODUCT 19', 99125, TO_TIMESTAMP('2014-02-13 19:15:34.372', 'yyyy-mm-dd hh24:mi.ss.ff'), 'Obacht! Dem flügge Sättigungsbeilage. Bagage und Waldschrat betören hochnäsig Augenschmaus. Dem blindwütig Ohrenschmaus festnageln. Das fatal Schwedenfilm. Des ausgemergelt Gemächt bauchpinseln. Hochstapler und Geschmeichen Jubelperser. Mumpitz und Libero abkupfern töricht Flegel. Dem blümerant Gedudel duellieren. Dem pfundig Aue frohlocken. Ei der Daus!');
INSERT INTO product_entity (product_uuid, user_uuid, tag_uuid, name, number_of_downloads, creation_date, description) VALUES (random_uuid(), '23c61362911e4438876507b019949570', '2D1EBC5B7D2741979CF0E84451C5BBB1', 'PRODUCT 20',  8025, TO_TIMESTAMP('2012-02-13 21:12:34.372', 'yyyy-mm-dd hh24:mi.ss.ff'), 'Eisbein anschwärzen bräsig Begrüßungsgeld. Das hanebüchen Jubelperser. Mumpitz und Libero abkupfern töricht Flegel. Dem blümerant Gedudel duellieren. Dem pfundig Aue frohlocken. Ei der Daus!');
INSERT INTO product_entity (product_uuid, user_uuid, tag_uuid, name, number_of_downloads, creation_date, description) VALUES (random_uuid(), '23c61362911e4438876507b019949570', '27497c552d0e4e8d88c68ad2721d94c7', 'PRODUCT 22',   925, TO_TIMESTAMP('2017-02-12 17:34:34.372', 'yyyy-mm-dd hh24:mi.ss.ff'), ' Das hanebüchen Jubelperser. Mumpitz und Libero abkupfern töricht Flegel. Dem blümerant Gedudel duellieren. Dem pfundig Aue frohlocken. Ei der Daus!');
INSERT INTO product_entity (product_uuid, user_uuid, tag_uuid, name, number_of_downloads, creation_date, description) VALUES (random_uuid(), 'c848cad7c3b2499a96888fb2a261313b', '27497c552d0e4e8d88c68ad2721d94c7', 'PRODUCT 32',  7725, TO_TIMESTAMP('2017-02-12 19:38:34.372', 'yyyy-mm-dd hh24:mi.ss.ff'), 'Obacht! Dem flügge Sättigungsbeilage. Bagage und Waldschrat betören hochnäsig Augenschmaus. Dem blindwütig Ohrenschmaus festnageln. Das fatal Schwedenfilm. Des ausgemergelt Gemächt bauchpinse!');
INSERT INTO product_entity (product_uuid, user_uuid, tag_uuid, name, number_of_downloads, creation_date, description) VALUES (random_uuid(), 'c848cad7c3b2499a96888fb2a261313b', '2D1EBC5B7D2741979CF0E84451C5BBB1', 'PRODUCT 42',   125, TO_TIMESTAMP('2016-02-13 03:21:34.372', 'yyyy-mm-dd hh24:mi.ss.ff'), 'Obacht! Das fatal Schwedenfilm. Des ausgemergelt Gemächt bauchpinseln. Hochstapler und Geschmeide verhaspeln altbacken Damenbart. Franzosenkrankheit und Lümmeltüte katzbuckeln bierernst Haudegen. Die Schabracke schlampampen des fidel Absacker. Fressalien und Eisbein anschwärzen bräsig Begrüßungsgeld. Das hanebüchen Jubelperser. Mumpitz und Libero abkupfern töricht Flegel. Dem blümerant Gedudel duellieren. Dem pfundig Aue frohlocken. Ei der Daus!');
INSERT INTO product_entity (product_uuid, user_uuid, tag_uuid, name, number_of_downloads, creation_date, description) VALUES (random_uuid(), 'c848cad7c3b2499a96888fb2a261313b', '2D1EBC5B7D2741979CF0E84451C5BBB1', 'PRODUCT 52',    25, TO_TIMESTAMP('2015-02-13 23:22:34.372', 'yyyy-mm-dd hh24:mi.ss.ff'), 'Obacht! Dem flügge Sättigungsbeilage. Bagage und Waldschrat idel Absacker. Fressalien und Eisbein anschwärzen bräsig Begrüßungsgeld. Das hanebüchen Jubelperser. Mumpitz und Libero abkupfern töricht Flegel. Dem blümerant Gedudel duellieren. Dem pfundig Aue frohlocken. Ei der Daus!');
INSERT INTO product_entity (product_uuid, user_uuid, tag_uuid, name, number_of_downloads, creation_date, description) VALUES (random_uuid(), 'c848cad7c3b2499a96888fb2a261313b', '2D1EBC5B7D2741979CF0E84451C5BBB1', 'PRODUCT 62', 12125, TO_TIMESTAMP('2017-01-13 12:32:34.372', 'yyyy-mm-dd hh24:mi.ss.ff'), 'Fressalien und Eisbein anschwärzen bräsig Begrüßungsgeld. Das hanebüchen Jubelperser. Mumpitz und Libero abkupfern töricht Flegel. Dem blümerant Gedudel duellieren. Dem pfundig Aue frohlocken. Ei der Daus!');
INSERT INTO product_entity (product_uuid, user_uuid, tag_uuid, name, number_of_downloads, creation_date, description) VALUES (random_uuid(), '23c61362911e4438876507b019949570', '27497c552d0e4e8d88c68ad2721d94c7', 'PRODUCT 72',  1125, TO_TIMESTAMP('2017-02-12 16:34:34.372', 'yyyy-mm-dd hh24:mi.ss.ff'), 'Obacht! Dem flügge SättigunGemächt bauchpinseln.');
INSERT INTO product_entity (product_uuid, user_uuid, tag_uuid, name, number_of_downloads, creation_date, description) VALUES (random_uuid(), '23c61362911e4438876507b019949570', '2D1EBC5B7D2741979CF0E84451C5BBB1', 'PRODUCT 82',     5, TO_TIMESTAMP('2017-02-11 17:45:34.372', 'yyyy-mm-dd hh24:mi.ss.ff'), 'Obacht! Dem flügge Sättiggemergelt Gemächt bauchpinseln. Hochstapler und Geschmeide verhaspeln altbacken Damenbart. Franzosenkrankheit und Lümmeltüte katzbuckeln bierernst Haudegen. Die Schabracke schlampampen des fidel Absacker. Ei der Daus!');
INSERT INTO product_entity (product_uuid, user_uuid, tag_uuid, name, number_of_downloads, creation_date, description) VALUES (random_uuid(), 'c848cad7c3b2499a96888fb2a261313b', '2D1EBC5B7D2741979CF0E84451C5BBB1', 'PRODUCT 92',    12, TO_TIMESTAMP('2015-12-13 18:08:34.372', 'yyyy-mm-dd hh24:mi.ss.ff'), 'Obacht! Dem flügge Sättigungsbeilage. as hanebüchen Jubelperser. Mumpitz und Libero abkupfern töricht Flegel. Dem blümerant Gedudel duellieren. Dem pfundig Aue frohlocken. Ei der Daus!');
INSERT INTO product_entity (product_uuid, user_uuid, tag_uuid, name, number_of_downloads, creation_date, description) VALUES (random_uuid(), 'c848cad7c3b2499a96888fb2a261313b', '27497c552d0e4e8d88c68ad2721d94c7', 'PRODUCT 21', 54125, TO_TIMESTAMP('2015-02-25 18:16:34.372', 'yyyy-mm-dd hh24:mi.ss.ff'), 'Obacht! Dem flügge Sättigungsbeilage. Bagage und Waldschrat betören hochnäsig Augenschmaus. Dem blindwütig Ohrenschmaus festnageln. Das fatal Schwedenfilm. Des ausgemergelt Gemächt bauchpinseln. Hochstapler und Geschmeide hanebüchen Jubelperser. Mumpitz und Libero abkupfern töricht Flegel. Dem blümerant Gedudel duellieren. Dem pfundig Aue frohlocken. Ei der Daus!');
INSERT INTO product_entity (product_uuid, user_uuid, tag_uuid, name, number_of_downloads, creation_date, description) VALUES (random_uuid(), 'c848cad7c3b2499a96888fb2a261313b', '2D1EBC5B7D2741979CF0E84451C5BBB1', 'PRODUCT 31', 99125, TO_TIMESTAMP('2014-02-13 19:15:34.372', 'yyyy-mm-dd hh24:mi.ss.ff'), 'Obacht! Dem flügge Sättigungsbeilage. Bagage und Waldschrat betören hochnäsig Augenschmaus. Dem blindwütig Ohrenschmaus festnageln. Das fatal Schwedenfilm. Des ausgemergelt Gemächt bauchpinseln. Hochstapler und Geschmeichen Jubelperser. Mumpitz und Libero abkupfern töricht Flegel. Dem blümerant Gedudel duellieren. Dem pfundig Aue frohlocken. Ei der Daus!');
INSERT INTO product_entity (product_uuid, user_uuid, tag_uuid, name, number_of_downloads, creation_date, description) VALUES (random_uuid(), '23c61362911e4438876507b019949570', '2D1EBC5B7D2741979CF0E84451C5BBB1', 'PRODUCT 41',  8025, TO_TIMESTAMP('2012-02-13 21:12:34.372', 'yyyy-mm-dd hh24:mi.ss.ff'), 'Eisbein anschwärzen bräsig Begrüßungsgeld. Das hanebüchen Jubelperser. Mumpitz und Libero abkupfern töricht Flegel. Dem blümerant Gedudel duellieren. Dem pfundig Aue frohlocken. Ei der Daus!');
INSERT INTO product_entity (product_uuid, user_uuid, tag_uuid, name, number_of_downloads, creation_date, description) VALUES (random_uuid(), '23c61362911e4438876507b019949570', '27497c552d0e4e8d88c68ad2721d94c7', 'PRODUCT 51',   925, TO_TIMESTAMP('2017-02-12 18:34:34.372', 'yyyy-mm-dd hh24:mi.ss.ff'), ' Das hanebüchen Jubelperser. Mumpitz und Libero abkupfern töricht Flegel. Dem blümerant Gedudel duellieren. Dem pfundig Aue frohlocken. Ei der Daus!');
INSERT INTO product_entity (product_uuid, user_uuid, tag_uuid, name, number_of_downloads, creation_date, description) VALUES (random_uuid(), 'c848cad7c3b2499a96888fb2a261313b', '27497c552d0e4e8d88c68ad2721d94c7', 'PRODUCT 61',  7725, TO_TIMESTAMP('2017-02-11 16:34:34.372', 'yyyy-mm-dd hh24:mi.ss.ff'), 'Obacht! Dem flügge Sättigungsbeilage. Bagage und Waldschrat betören hochnäsig Augenschmaus. Dem blindwütig Ohrenschmaus festnageln. Das fatal Schwedenfilm. Des ausgemergelt Gemächt bauchpinse!');
INSERT INTO product_entity (product_uuid, user_uuid, tag_uuid, name, number_of_downloads, creation_date, description) VALUES (random_uuid(), 'c848cad7c3b2499a96888fb2a261313b', '2D1EBC5B7D2741979CF0E84451C5BBB1', 'PRODUCT 71',   125, TO_TIMESTAMP('2016-02-13 03:21:34.372', 'yyyy-mm-dd hh24:mi.ss.ff'), 'Obacht! Das fatal Schwedenfilm. Des ausgemergelt Gemächt bauchpinseln. Hochstapler und Geschmeide verhaspeln altbacken Damenbart. Franzosenkrankheit und Lümmeltüte katzbuckeln bierernst Haudegen. Die Schabracke schlampampen des fidel Absacker. Fressalien und Eisbein anschwärzen bräsig Begrüßungsgeld. Das hanebüchen Jubelperser. Mumpitz und Libero abkupfern töricht Flegel. Dem blümerant Gedudel duellieren. Dem pfundig Aue frohlocken. Ei der Daus!');
INSERT INTO product_entity (product_uuid, user_uuid, name, number_of_downloads, creation_date, description) VALUES (random_uuid(), 'c848cad7c3b2499a96888fb2a261313b', 'PRODUCT 81',    25, TO_TIMESTAMP('2015-02-13 23:22:34.372', 'yyyy-mm-dd hh24:mi.ss.ff'), 'Obacht! Dem flügge Sättigungsbeilage. Bagage und Waldschrat idel Absacker. Fressalien und Eisbein anschwärzen bräsig Begrüßungsgeld. Das hanebüchen Jubelperser. Mumpitz und Libero abkupfern töricht Flegel. Dem blümerant Gedudel duellieren. Dem pfundig Aue frohlocken. Ei der Daus!');
INSERT INTO product_entity (product_uuid, user_uuid, name, number_of_downloads, creation_date, description) VALUES (random_uuid(), 'c848cad7c3b2499a96888fb2a261313b', 'PRODUCT 91', 12125, TO_TIMESTAMP('2017-01-13 12:32:34.372', 'yyyy-mm-dd hh24:mi.ss.ff'), 'Fressalien und Eisbein anschwärzen bräsig Begrüßungsgeld. Das hanebüchen Jubelperser. Mumpitz und Libero abkupfern töricht Flegel. Dem blümerant Gedudel duellieren. Dem pfundig Aue frohlocken. Ei der Daus!');
INSERT INTO product_entity (product_uuid, user_uuid, name, number_of_downloads, creation_date, description) VALUES (random_uuid(), '23c61362911e4438876507b019949570', 'PRODUCT 23',  1125, TO_TIMESTAMP('2017-02-12 16:34:34.372', 'yyyy-mm-dd hh24:mi.ss.ff'), 'Obacht! Dem flügge SättigunGemächt bauchpinseln.');
INSERT INTO product_entity (product_uuid, user_uuid, name, number_of_downloads, creation_date, description) VALUES (random_uuid(), '23c61362911e4438876507b019949570', 'PRODUCT 33',     5, TO_TIMESTAMP('2017-02-11 17:45:34.372', 'yyyy-mm-dd hh24:mi.ss.ff'), 'Obacht! Dem flügge Sättiggemergelt Gemächt bauchpinseln. Hochstapler und Geschmeide verhaspeln altbacken Damenbart. Franzosenkrankheit und Lümmeltüte katzbuckeln bierernst Haudegen. Die Schabracke schlampampen des fidel Absacker. Ei der Daus!');
INSERT INTO product_entity (product_uuid, user_uuid, name, number_of_downloads, creation_date, description) VALUES (random_uuid(), 'c848cad7c3b2499a96888fb2a261313b', 'product 43',    12, TO_TIMESTAMP('2015-12-13 18:08:34.372', 'yyyy-mm-dd hh24:mi.ss.ff'), 'Obacht! Dem flügge Sättigungsbeilage. as hanebüchen Jubelperser. Mumpitz und Libero abkupfern töricht Flegel. Dem blümerant Gedudel duellieren. Dem pfundig Aue frohlocken. Ei der Daus!');
INSERT INTO product_entity (product_uuid, user_uuid, name, number_of_downloads, creation_date, description) VALUES (random_uuid(), 'c848cad7c3b2499a96888fb2a261313b', 'prODUCt 53', 54125, TO_TIMESTAMP('2015-02-25 18:16:34.372', 'yyyy-mm-dd hh24:mi.ss.ff'), 'Obacht! Dem flügge Sättigungsbeilage. Bagage und Waldschrat betören hochnäsig Augenschmaus. Dem blindwütig Ohrenschmaus festnageln. Das fatal Schwedenfilm. Des ausgemergelt Gemächt bauchpinseln. Hochstapler und Geschmeide hanebüchen Jubelperser. Mumpitz und Libero abkupfern töricht Flegel. Dem blümerant Gedudel duellieren. Dem pfundig Aue frohlocken. Ei der Daus!');
INSERT INTO product_entity (product_uuid, user_uuid, name, number_of_downloads, creation_date, description) VALUES (random_uuid(), 'c848cad7c3b2499a96888fb2a261313b', 'prODUCt 63', 99125, TO_TIMESTAMP('2014-02-13 19:15:34.372', 'yyyy-mm-dd hh24:mi.ss.ff'), 'Obacht! Dem flügge Sättigungsbeilage. Bagage und Waldschrat betören hochnäsig Augenschmaus. Dem blindwütig Ohrenschmaus festnageln. Das fatal Schwedenfilm. Des ausgemergelt Gemächt bauchpinseln. Hochstapler und Geschmeichen Jubelperser. Mumpitz und Libero abkupfern töricht Flegel. Dem blümerant Gedudel duellieren. Dem pfundig Aue frohlocken. Ei der Daus!');
INSERT INTO product_entity (product_uuid, user_uuid, name, number_of_downloads, creation_date, description) VALUES (random_uuid(), '23c61362911e4438876507b019949570', 'prODUCt 73',  8025, TO_TIMESTAMP('2012-02-13 21:12:34.372', 'yyyy-mm-dd hh24:mi.ss.ff'), 'Eisbein anschwärzen bräsig Begrüßungsgeld. Das hanebüchen Jubelperser. Mumpitz und Libero abkupfern töricht Flegel. Dem blümerant Gedudel duellieren. Dem pfundig Aue frohlocken. Ei der Daus!');
INSERT INTO product_entity (product_uuid, user_uuid, name, number_of_downloads, creation_date, description) VALUES (random_uuid(), '23c61362911e4438876507b019949570', 'prODUCt 83',   925, TO_TIMESTAMP('2017-02-12 22:34:34.372', 'yyyy-mm-dd hh24:mi.ss.ff'), ' Das hanebüchen Jubelperser. Mumpitz und Libero abkupfern töricht Flegel. Dem blümerant Gedudel duellieren. Dem pfundig Aue frohlocken. Ei der Daus!');
INSERT INTO product_entity (product_uuid, user_uuid, name, number_of_downloads, creation_date, description) VALUES (random_uuid(), 'c848cad7c3b2499a96888fb2a261313b', 'Product 93',  7725, TO_TIMESTAMP('2017-02-12 13:34:34.372', 'yyyy-mm-dd hh24:mi.ss.ff'), 'Obacht! Dem flügge Sättigungsbeilage. Bagage und Waldschrat betören hochnäsig Augenschmaus. Dem blindwütig Ohrenschmaus festnageln. Das fatal Schwedenfilm. Des ausgemergelt Gemächt bauchpinse!');


/**
 * insert rating
 */
INSERT INTO rating_entity (rating_uuid, rating_as_number, user_uuid, product_uuid, rating_description) VALUES (random_uuid(), 5, 'c848cad7c3b2499a96888fb2a261313b', '8650caf1f023480895f7322af55fb163', 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.');
INSERT INTO rating_entity (rating_uuid, rating_as_number, user_uuid, product_uuid, rating_description) VALUES (random_uuid(), 6, '23c61362911e4438876507b019949570', '14144bb2892f4657bcd09ead9066f92a', 'Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.');
INSERT INTO rating_entity (rating_uuid, rating_as_number, user_uuid, product_uuid, rating_description) VALUES (random_uuid(), 7, 'c848cad7c3b2499a96888fb2a261313b', 'a625e6f431ea49beb71eeee54e283c43', 'Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.');
INSERT INTO rating_entity (rating_uuid, rating_as_number, user_uuid, product_uuid, rating_description) VALUES (random_uuid(), 8, '23c61362911e4438876507b019949570', 'b90bb1f16f7e40a786a33675d4dea7c5', 'Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.');
INSERT INTO rating_entity (rating_uuid, rating_as_number, user_uuid, product_uuid, rating_description) VALUES (random_uuid(), 9, 'c848cad7c3b2499a96888fb2a261313b', 'f9e90ce0a0e94296868b05314cb60b5a', 'Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis.');
INSERT INTO rating_entity (rating_uuid, rating_as_number, user_uuid, product_uuid, rating_description) VALUES (random_uuid(), 3, '23c61362911e4438876507b019949570', '4c049192929d4a498f17c285928fc769', 'At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, At accusam aliquyam diam diam dolore dolores duo eirmod eos erat, et nonumy sed tempor et et invidunt justo labore Stet clita ea et gubergren, kasd magna no rebum. sanctus sea sed takimata ut vero voluptua. est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat.');
INSERT INTO rating_entity (rating_uuid, rating_as_number, user_uuid, product_uuid, rating_description) VALUES (random_uuid(), 4, 'c848cad7c3b2499a96888fb2a261313b', '0d36b243aa29407e89d6666e164c5118', 'Consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus.');
INSERT INTO rating_entity (rating_uuid, rating_as_number, user_uuid, product_uuid, rating_description) VALUES (random_uuid(), 1, '23c61362911e4438876507b019949570', '6370604e1d584e5bb1b297fd54fb59b5', 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.');
INSERT INTO rating_entity (rating_uuid, rating_as_number, user_uuid, product_uuid, rating_description) VALUES (random_uuid(), 5, 'c848cad7c3b2499a96888fb2a261313b', '105b789e84c545bf8722108533a81530', 'Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.');
INSERT INTO rating_entity (rating_uuid, rating_as_number, user_uuid, product_uuid, rating_description) VALUES (random_uuid(), 9, '23c61362911e4438876507b019949570', '8650caf1f023480895f7322af55fb163', 'Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.');
INSERT INTO rating_entity (rating_uuid, rating_as_number, user_uuid, product_uuid, rating_description) VALUES (random_uuid(), 8, '23c61362911e4438876507b019949570', '14144bb2892f4657bcd09ead9066f92a', 'Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.');
INSERT INTO rating_entity (rating_uuid, rating_as_number, user_uuid, product_uuid, rating_description) VALUES (random_uuid(), 9, 'c848cad7c3b2499a96888fb2a261313b', 'a625e6f431ea49beb71eeee54e283c43', 'Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis.');
INSERT INTO rating_entity (rating_uuid, rating_as_number, user_uuid, product_uuid, rating_description) VALUES (random_uuid(), 3, '23c61362911e4438876507b019949570', 'b90bb1f16f7e40a786a33675d4dea7c5', 'At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, At accusam aliquyam diam diam dolore dolores duo eirmod eos erat, et nonumy sed tempor et et invidunt justo labore Stet clita ea et gubergren, kasd magna no rebum. sanctus sea sed takimata ut vero voluptua. est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat.');
INSERT INTO rating_entity (rating_uuid, rating_as_number, user_uuid, product_uuid, rating_description) VALUES (random_uuid(), 4, 'c848cad7c3b2499a96888fb2a261313b', 'f9e90ce0a0e94296868b05314cb60b5a', 'Consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus.');
INSERT INTO rating_entity (rating_uuid, rating_as_number, user_uuid, product_uuid, rating_description) VALUES (random_uuid(), 1, '23c61362911e4438876507b019949570', '4c049192929d4a498f17c285928fc769', 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.');
INSERT INTO rating_entity (rating_uuid, rating_as_number, user_uuid, product_uuid, rating_description) VALUES (random_uuid(), 5, 'c848cad7c3b2499a96888fb2a261313b', '0d36b243aa29407e89d6666e164c5118', 'Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.');
INSERT INTO rating_entity (rating_uuid, rating_as_number, user_uuid, product_uuid, rating_description) VALUES (random_uuid(), 9, '23c61362911e4438876507b019949570', '6370604e1d584e5bb1b297fd54fb59b5', 'Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.');
INSERT INTO rating_entity (rating_uuid, rating_as_number, user_uuid, product_uuid, rating_description) VALUES (random_uuid(), 5, 'c848cad7c3b2499a96888fb2a261313b', '8650caf1f023480895f7322af55fb163', 'Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.');
INSERT INTO rating_entity (rating_uuid, rating_as_number, user_uuid, product_uuid, rating_description) VALUES (random_uuid(), 6, '23c61362911e4438876507b019949570', '14144bb2892f4657bcd09ead9066f92a', 'Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis.');
INSERT INTO rating_entity (rating_uuid, rating_as_number, user_uuid, product_uuid, rating_description) VALUES (random_uuid(), 7, 'c848cad7c3b2499a96888fb2a261313b', 'a625e6f431ea49beb71eeee54e283c43', 'At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, At accusam aliquyam diam diam dolore dolores duo eirmod eos erat, et nonumy sed tempor et et invidunt justo labore Stet clita ea et gubergren, kasd magna no rebum. sanctus sea sed takimata ut vero voluptua. est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat.');
INSERT INTO rating_entity (rating_uuid, rating_as_number, user_uuid, product_uuid, rating_description) VALUES (random_uuid(), 8, '23c61362911e4438876507b019949570', 'b90bb1f16f7e40a786a33675d4dea7c5', 'Consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus.');
INSERT INTO rating_entity (rating_uuid, rating_as_number, user_uuid, product_uuid, rating_description) VALUES (random_uuid(), 9, 'c848cad7c3b2499a96888fb2a261313b', 'f9e90ce0a0e94296868b05314cb60b5a', 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.');
INSERT INTO rating_entity (rating_uuid, rating_as_number, user_uuid, product_uuid, rating_description) VALUES (random_uuid(), 3, '23c61362911e4438876507b019949570', '4c049192929d4a498f17c285928fc769', 'Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.');
INSERT INTO rating_entity (rating_uuid, rating_as_number, user_uuid, product_uuid, rating_description) VALUES (random_uuid(), 4, 'c848cad7c3b2499a96888fb2a261313b', '0d36b243aa29407e89d6666e164c5118', 'Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.');
INSERT INTO rating_entity (rating_uuid, rating_as_number, user_uuid, product_uuid, rating_description) VALUES (random_uuid(), 1, '23c61362911e4438876507b019949570', '6370604e1d584e5bb1b297fd54fb59b5', 'Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.');
INSERT INTO rating_entity (rating_uuid, rating_as_number, user_uuid, product_uuid, rating_description) VALUES (random_uuid(), 5, 'c848cad7c3b2499a96888fb2a261313b', '105b789e84c545bf8722108533a81530', 'Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis.');
INSERT INTO rating_entity (rating_uuid, rating_as_number, user_uuid, product_uuid, rating_description) VALUES (random_uuid(), 9, '23c61362911e4438876507b019949570', '8650caf1f023480895f7322af55fb163', 'At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, At accusam aliquyam diam diam dolore dolores duo eirmod eos erat, et nonumy sed tempor et et invidunt justo labore Stet clita ea et gubergren, kasd magna no rebum. sanctus sea sed takimata ut vero voluptua. est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat.');
INSERT INTO rating_entity (rating_uuid, rating_as_number, user_uuid, product_uuid, rating_description) VALUES (random_uuid(), 8, '23c61362911e4438876507b019949570', '14144bb2892f4657bcd09ead9066f92a', 'Consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus.');
INSERT INTO rating_entity (rating_uuid, rating_as_number, user_uuid, product_uuid, rating_description) VALUES (random_uuid(), 9, 'c848cad7c3b2499a96888fb2a261313b', 'a625e6f431ea49beb71eeee54e283c43', 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.');
INSERT INTO rating_entity (rating_uuid, rating_as_number, user_uuid, product_uuid, rating_description) VALUES (random_uuid(), 3, '23c61362911e4438876507b019949570', 'b90bb1f16f7e40a786a33675d4dea7c5', 'Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.');
INSERT INTO rating_entity (rating_uuid, rating_as_number, user_uuid, product_uuid, rating_description) VALUES (random_uuid(), 4, 'c848cad7c3b2499a96888fb2a261313b', 'f9e90ce0a0e94296868b05314cb60b5a', 'Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.');
INSERT INTO rating_entity (rating_uuid, rating_as_number, user_uuid, product_uuid, rating_description) VALUES (random_uuid(), 1, '23c61362911e4438876507b019949570', '4c049192929d4a498f17c285928fc769', 'Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.');
INSERT INTO rating_entity (rating_uuid, rating_as_number, user_uuid, product_uuid, rating_description) VALUES (random_uuid(), 5, 'c848cad7c3b2499a96888fb2a261313b', '0d36b243aa29407e89d6666e164c5118', 'Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis.');
INSERT INTO rating_entity (rating_uuid, rating_as_number, user_uuid, product_uuid, rating_description) VALUES (random_uuid(), 9, '23c61362911e4438876507b019949570', '6370604e1d584e5bb1b297fd54fb59b5', 'At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, At accusam aliquyam diam diam dolore dolores duo eirmod eos erat, et nonumy sed tempor et et invidunt justo labore Stet clita ea et gubergren, kasd magna no rebum. sanctus sea sed takimata ut vero voluptua. est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat.');







































