package rocks.inspectit.marketplace.dao.mocks;

import org.springframework.stereotype.Repository;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ThreadLocalRandom;
import java.util.stream.Stream;

import rocks.inspectit.marketplace.mvc.angular.model.DashBoardModel;

/**
 * Will be deleted soon.
 *
 * @author NKO
 * @version %I%, %G%
 * @since 1.X-SNAPSHOT
 */
@Repository
public class MockRepository {

	public List<DashBoardModel> getMockedDashBoardValues() {
		final List list = new ArrayList<DashBoardModel>();
		Stream.iterate(0, i -> i + 1).limit(10).forEach(i -> {
			final DashBoardModel d = new DashBoardModel();
			d.setCreationUser(this.getClass().getName());
			d.setCreationDate(LocalDateTime.now());
			d.setDescription("Generated by MockRepository for test and demo purposes, since we have no database and entities, yet!");
			d.setName("Mock Config " + i);
			d.setRating(ThreadLocalRandom.current().nextDouble(1, 5));
			list.add(d);
		});
		return list;
	}

}
